<?xml version="1.0" encoding="utf-8"?><Database Name="Items" Class="ItemLINQDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=&quot;|DataDirectory|\Database Files\Items.mdf&quot;;Integrated Security=True" SettingsObjectName="TTRPG_Helper.Properties.Settings" SettingsPropertyName="ItemsConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Items" Member="Items">
    <Type Name="Item">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ItemName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ItemType" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ArmorClassProvided" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AttackDiceAmount" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AttackDiceSize" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Quantity" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Cost" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="OwnerId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>